// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openApp() : Promise<void> {
    await TAURI_INVOKE("open_app");
},
async isMainWindowHidden() : Promise<boolean> {
    return await TAURI_INVOKE("is_main_window_hidden");
},
async openSettings() : Promise<void> {
    await TAURI_INVOKE("open_settings");
},
async getDeviceName(id: string) : Promise<[string, InterfaceType[]] | null> {
    return await TAURI_INVOKE("get_device_name", { id });
},
async getMacName() : Promise<string | null> {
    return await TAURI_INVOKE("get_mac_name");
},
async switchTheme(theme: Theme) : Promise<void> {
    await TAURI_INVOKE("switch_theme", { theme });
},
async getDetailById(id: number) : Promise<Result<ChargingHistoryDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_detail_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllChargingHistory() : Promise<Result<ChargingHistory[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_charging_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBatteryHealthHistory() : Promise<Result<BatteryHealthSnapshot[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_battery_health_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Top energy-consuming processes. Takes ~1.5s because `top` needs two
 * samples, so the frontend should call this on demand, not on a timer.
 */
async getProcessEnergy() : Promise<ProcessEnergy[]> {
    return await TAURI_INVOKE("get_process_energy");
},
/**
 * Resize the status bar panel to fit its content.
 * 
 * The panel is an `NSPopover` whose size is fixed from the window frame when
 * it is created, so the web view cannot grow it by itself. The web view
 * measures its content and asks for the height it needs; the width is kept.
 */
async setPopoverHeight(height: number) : Promise<void> {
    await TAURI_INVOKE("set_popover_height", { height });
},
async deleteHistoryById(id: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
deviceEvent: DeviceEvent,
devicePowerTickEvent: DevicePowerTickEvent,
historyRecordedEvent: HistoryRecordedEvent,
powerTickEvent: PowerTickEvent,
powerUpdatedEvent: PowerUpdatedEvent,
preferenceEvent: PreferenceEvent,
systemTickEvent: SystemTickEvent,
windowLoadedEvent: WindowLoadedEvent
}>({
deviceEvent: "device-event",
devicePowerTickEvent: "device-power-tick-event",
historyRecordedEvent: "history-recorded-event",
powerTickEvent: "power-tick-event",
powerUpdatedEvent: "power-updated-event",
preferenceEvent: "preference-event",
systemTickEvent: "system-tick-event",
windowLoadedEvent: "window-loaded-event"
})

/** user-defined constants **/



/** user-defined types **/

export type Action = 
/**
 * A device has attached. The device reference belongs to the
 * client. It must be explicitly released, or else it will leak.
 */
"Attached" | 
/**
 * A device has detached. The device object delivered will be
 * the same as the one delivered in the Attached notification. This
 * device reference does not need to be released.
 */
"Detached" | 
/**
 * This notification is delivered in response to
 * 
 * 1. A call to am::DeviceNotificationUnsubscribe().
 * 2. An error occurred on one of the underlying notification systems
 * (i.e. usbmuxd or mDNSResponder crashed or stopped responding).
 * Unsubcribing and resubscribing may recover the notification system.
 */
"NotificationStopped" | "Paired"
export type BatteryHealthSnapshot = { day: string; timestamp: number; maxCapacity: number; designCapacity: number; cycleCount: number }
export type ChargingHistory = { id: number; fromLevel: number; endLevel: number; chargingTime: number; timestamp: number; name: string; udid: string; isRemote: number; adapterName: string }
export type ChargingHistoryDetail = { avg: NormalizedData; peak: NormalizedData; curve: NormalizedResource[]; raw: string[] }
export type CoreUsage = { usage: number; 
/**
 * True for an efficiency core. Always false on Intel, which has none.
 */
efficiency: boolean }
export type CpuStats = { 
/**
 * Whole-machine busy share, 0-100.
 */
usage: number; 
/**
 * Per logical core, in kernel order.
 */
cores: CoreUsage[] }
export type DeviceEvent = { udid: string; name: string; interface: InterfaceType; action: Action }
export type DevicePowerTickEvent = { udid: string; data: NormalizedResource }
export type Duration = { secs: number; nanos: number }
export type GpuStats = { 
/**
 * 0-100.
 */
usage: number; 
/**
 * Bytes of memory the GPU driver has in use; 0 if not reported.
 */
memoryUsed: number }
export type HistoryRecordedEvent = null
export type InterfaceType = "Unknown" | "USB" | "WiFi"
export type MemoryPressure = "normal" | "warning" | "critical"
/**
 * Sizes in bytes. `used` follows Activity Monitor: app + wired + compressed.
 */
export type MemoryStats = { total: number; used: number; app: number; wired: number; compressed: number; swapUsed: number; pressure: MemoryPressure }
export type NetworkStats = { 
/**
 * Bytes per second.
 */
downRate: number; upRate: number; 
/**
 * Bytes since boot, over the counted interfaces.
 */
totalDown: number; totalUp: number; 
/**
 * The busiest counted interface in this sample, e.g. `en0`.
 */
interface: string | null }
export type NormalizedData = { systemIn: number; systemLoad: number; batteryPower: number; adapterPower: number; efficiencyLoss: number; 
/**
 * 0 if not available
 */
brightnessPower: number; 
/**
 * 0 if not available
 */
heatpipePower: number; batteryLevel: number; absoluteBatteryLevel: number; temperature: number; adapterWatts: number; adapterVoltage: number; adapterAmperage: number }
export type NormalizedResource = ({ systemIn: number; systemLoad: number; batteryPower: number; adapterPower: number; efficiencyLoss: number; 
/**
 * 0 if not available
 */
brightnessPower: number; 
/**
 * 0 if not available
 */
heatpipePower: number; batteryLevel: number; absoluteBatteryLevel: number; temperature: number; adapterWatts: number; adapterVoltage: number; adapterAmperage: number }) & { isLocal: boolean; isCharging: boolean; 
/**
 * True when the pack is full. Distinct from `is_charging`, which is
 * false while resting on the adapter at 100%.
 */
fullyCharged?: boolean; 
/**
 * True when an adapter is plugged in, whether or not it is charging.
 */
externalConnected?: boolean; timeRemain: Duration; timeRemainKnown: boolean; lastUpdate: number; adapterName: string | null; 
/**
 * Adapter model description, e.g. "pd charger".
 */
adapterDescription?: string | null; 
/**
 * Negotiated USB-C PD power tier.
 */
adapterPowerTier?: number; adapterIsWireless?: boolean; cycleCount: number; currentCapacity: number; maxCapacity: number; designCapacity?: number }
export type PowerTickEvent = { data: NormalizedResource }
export type PowerUpdatedEvent = TrayLabel
export type PreferenceEvent = { theme: Theme } | { animationsEnabled: boolean } | { updateInterval: number } | { language: string } | { statusBarItem: StatusBarItem } | { statusBarShowCharging: boolean } | { systemMonitorEnabled: boolean } | { statusBarSystem: StatusBarSystem }
export type ProcessEnergy = { pid: number; name: string; 
/**
 * Energy impact, in the same arbitrary units Activity Monitor uses.
 * Comparable between processes, not a wattage.
 */
impact: number; 
/**
 * CPU share from the same `top` sample, where 100 is one full core.
 */
cpu: number; 
/**
 * Memory footprint in bytes, as `top`'s MEM column reports it.
 */
memory: number }
/**
 * Which power metric to show in the status bar.
 * 
 * Implements a forgiving `Deserialize`: unknown or non-string values (e.g. a
 * stale `"none"` or `null` persisted by older builds) fall back to `System`
 * instead of panicking inside tauri-specta and killing the power-tick task.
 */
export type StatusBarItem = "system" | "screen" | "heatpipe"
/**
 * What, besides power, the status bar title shows.
 * 
 * Deserialisation is forgiving for the same reason as `StatusBarItem`: a bad
 * persisted value must not panic the power-tick task.
 */
export type StatusBarSystem = "none" | "cpu" | "network" | "compact"
export type SystemStats = { cpu: CpuStats; 
/**
 * `None` when no accelerator reports utilisation.
 */
gpu: GpuStats | null; memory: MemoryStats; network: NetworkStats }
export type SystemTickEvent = { data: SystemStats }
export type Theme = "light" | "dark" | "system"
/**
 * What the status bar shows. Built on the power tick, drawn on the main
 * thread.
 */
export type TrayLabel = { 
/**
 * The power reading, e.g. `12.3w`.
 */
primary: string; 
/**
 * Two-line stacks drawn after it, e.g. `[["↓1.2M", "↑86K"]]`.
 */
stacks: ([string, string])[] }
export type WindowLoadedEvent = null

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
